linters:
  enable-all: true

linters-settings:
  misspell:
    locale: US
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com
          - golang.org

run:
  go: '1.21'
  timeout: 1m
