linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - exhaustruct
    - gochecknoglobals
    - nlreturn

linters-settings:
  maligned:
    suggest-new: true
  misspell:
    locale: US
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com

run:
  go: '1.21'
  timeout: 1m
