linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - exhaustruct
    - gochecknoglobals
    - nlreturn

linters-settings:
  maligned:
    suggest-new: true
  misspell:
    locale: US

run:
  go: '1.19'
  timeout: 1m
