name: Lint & Test
on: [ push ]
jobs:
  lint-test:
    runs-on: ubuntu-latest
    container:
      image: golangci/golangci-lint:latest
    steps:
      - uses: actions/checkout@v3
      - run: make lint
      - run: make test
